#!/bin/bash
set -e

APP_DB=${APP_POSTGRES_DB:-devslave_app}
TEST_DB=${TEST_POSTGRES_DB:-devslave_test}

if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<- EOSQL
			CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
			ALTER ROLE ${POSTGRES_NON_ROOT_USER} CREATEDB;
			GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
			GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
			CREATE DATABASE ${APP_DB} OWNER ${POSTGRES_NON_ROOT_USER};
			CREATE DATABASE ${TEST_DB} OWNER ${POSTGRES_NON_ROOT_USER};
			GRANT ALL PRIVILEGES ON DATABASE ${APP_DB} TO ${POSTGRES_NON_ROOT_USER};
			GRANT ALL PRIVILEGES ON DATABASE ${TEST_DB} TO ${POSTGRES_NON_ROOT_USER};
			\c ${APP_DB}
			GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
			\c ${TEST_DB}
			GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
	EOSQL
else
    echo "SETUP INFO: No Environment variables given!"
fi
