#!/usr/bin/env bash
set -euo pipefail

# Args
project_path=$1
if [[ -z "${project_path}" ]]; then
  echo "Usage: $0 <project_path>" >&2
  exit 1
fi

# Resolve repo root (this script lives in src/scripts/setup)
script_dir="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "${script_dir}/../../.." && pwd)"

# Run basic setup
source "$repo_root/src/scripts/setup/setup-default.sh"

# Setup nvm and Node.js
if [[ -f ~/.nvm/nvm.sh ]]; then
  source ~/.nvm/nvm.sh
  
  # Create .nvmrc if it doesn't exist
  if [[ ! -f .nvmrc ]]; then
    echo "lts/*" > .nvmrc
    echo "Created .nvmrc file"
  else
    echo ".nvmrc already exists, skipping"
  fi
  
  # Install Node.js if not already installed for this version
  if ! nvm which "$(cat .nvmrc)" >/dev/null 2>&1; then
    nvm install
    echo "Installed Node.js version $(cat .nvmrc)"
  else
    nvm use
    echo "Node.js version $(cat .nvmrc) already installed"
  fi
else
  echo "Warning: nvm not found at ~/.nvm/nvm.sh, skipping Node.js setup"
fi

# Setup npm package.json
if [[ ! -f package.json ]]; then
  npm init -y
  echo "Created package.json"
else
  echo "package.json already exists, skipping npm init"
fi

# Create project structure
mkdir -p src
mkdir -p tests

# Setup gitignore (append Node.js rules if not already present)
node_gitignore_marker="# Node.js gitignore rules"
if [[ ! -f .gitignore ]] || ! grep -q "$node_gitignore_marker" .gitignore; then
  echo "Adding Node.js gitignore rules"
  cat << EOF >> .gitignore

$node_gitignore_marker
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# next.js build output
.next

# nuxt.js build output
.nuxt

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/
EOF
else
  echo "Node.js gitignore rules already present, skipping"
fi

# Add and commit changes (only if there are changes)
git add -A
if git diff --cached --quiet; then
  echo "No changes to commit"
else
  git commit -m "chore: add node setup" --no-gpg-sign || true
  echo "Committed Node.js setup changes"
fi